# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikithon', '0002_add_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('AVL', 'Available'), ('RES', 'Reserved'), ('SUB', 'Submitted'), ('PUB', 'Published'), ('REJ', 'Rejected')], default='AVL', max_length=3),
        ),
    ]
