# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=100, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0625\u0646\u062c\u0644\u064a\u0632\u064a')),
                ('ar_name', models.CharField(blank=True, max_length=100, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0639\u0631\u0628\u064a')),
                ('quality', models.CharField(blank=True, max_length=100, verbose_name='\u0627\u0644\u062c\u0648\u062f\u0629')),
                ('importance', models.CharField(blank=True, max_length=100, verbose_name='\u0627\u0644\u0623\u0647\u0645\u064a\u0629')),
                ('word_count', models.IntegerField(null=True, verbose_name='\u0639\u062f\u062f \u0627\u0644\u0643\u0644\u0645\u0627\u062a')),
                ('is_available', models.BooleanField(default=True, verbose_name='\u0645\u062a\u0648\u0641\u0631\u0629\u061f')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0640/\u0640\u0629')),
            ],
            options={
                'verbose_name': '\u0645\u0642\u0627\u0644\u0629',
                'verbose_name_plural': '\u0645\u0642\u0627\u0644\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0627\u0627\u0644\u0627\u0633\u0645')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='\u0627\u0644\u0631\u0627\u0628\u0637')),
            ],
            options={
                'verbose_name': '\u062a\u0635\u0646\u064a\u0641',
                'verbose_name_plural': '\u062a\u0635\u0627\u0646\u064a\u0641',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='\u062a\u0639\u0644\u064a\u0642')),
                ('reservation_date', models.DateTimeField(auto_now=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062d\u062c\u0632')),
                ('submission_date', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0625\u0631\u0633\u0627\u0644')),
                ('status', models.CharField(choices=[('RES', '\u0645\u062d\u062c\u0648\u0632\u0629'), ('SUB', '\u0623\u0631\u0633\u0644\u062a'), ('PUB', '\u0645\u0646\u0634\u0648\u0631\u0629'), ('REJ', '\u0645\u0631\u0641\u0648\u0636\u0629')], default='AVL', max_length=3, verbose_name='\u0627\u0644\u062d\u0627\u0644\u0629')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='\u0627\u0644\u0645\u0642\u0627\u0644\u0629')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_submitted', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0640/\u0640\u0629')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0640/\u0640\u0629')),
            ],
            options={
                'verbose_name': '\u062d\u062c\u0632',
                'verbose_name_plural': '\u062d\u062c\u0648\u0632\u0627\u062a',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='\u0627\u0644\u062a\u0635\u0646\u064a\u0641'),
        ),
    ]
