# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:13
from __future__ import unicode_literals
from django.db import models, migrations


def add_categories(apps, schema_editor):
    Category = apps.get_model('articles','Category')

    Category.objects.create(slug="obstetrics",
                            name="طب التوليد ")
    Category.objects.create(slug="gynecology",
                            name="علوم النساء")
    Category.objects.create(slug="cardiology",
                            name="علوم القلب")
    Category.objects.create(slug="radiology",
                            name="علم الأشعة")
    Category.objects.create(slug="urology",
                            name="علوم المسالك البلوية")
    Category.objects.create(slug="nephrology",
                            name="علوم الكلى")
    Category.objects.create(slug="digestive system",
                            name="طب الجهاز الهضمي")
    Category.objects.create(slug="pulmonology",
                            name="علوم التنفس ")
    Category.objects.create(slug="neurology",
                            name="علوم الأعصاب")
    Category.objects.create(slug="oncology",
                            name="علوم الأورام")
    Category.objects.create(slug="geriatrics",
                            name="طب المسنين")
    Category.objects.create(slug="endocrinology",
                            name="علوم الغدد")

def remove_categories(apps, schema_editor):
    Category = apps.get_model('articles','Category')
    Category.objects.filter(slug__in=["obstetrics", "gynecology",
                                           "cardiology", "radiology",
                                           "urology", "nephrology",
                                           "gastroenterology",
                                           "pulmonology", "endocrinology",
                                           "neurology",
                                           "oncology", "geriatrics"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(
            add_categories,
            reverse_code=remove_categories),
    ]
