# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:13
from __future__ import unicode_literals

from django.db import models, migrations



def add_categories(apps):
    Category = apps.get_model('Category')

    if not Category.objects.exists():
        Category.objects.create(code_name="obstetrics",
                                name="طب التوليد ")
        Category.objects.create(code_name="gynecology",
                                name="طب النساء")
        Category.objects.create(code_name="cardiology",
                                name="طب القلب")
        Category.objects.create(code_name="radiology",
                                name="علم الأشعة")
        Category.objects.create(code_name="urology",
                                name="طب الجهاز البولي")
        Category.objects.create(code_name="nephrology",
                                name="طب الكلى")
        Category.objects.create(code_name="digestive system",
                                name="الجهاز الهضمي")
        Category.objects.create(code_name="respiratory system",
                                name="الجهاز التنفسي ")
        Category.objects.create(code_name="nervous system",
                                name="الجهاز العصبي ")
        Category.objects.create(code_name="oncology",
                                name="علم الأورام ")
        Category.objects.create(code_name="geriatrics",
                                name="طب المسنين")
        Category.objects.create(code_name="endocrin system",
                                name=" الغدد")
def remove_categories(apps, schema_editor):
    Category = apps.get_model('Category')
    Category.objects.filter(code_name__in=["obstetrics", "gynecology", "cardiology",
                                           "radiology", "urology", "nephrology",
                                           "digestive system", "respiratory system","endocrin system",
                                           "nervous system", "oncology","geriatrics",
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('wikithon', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(
            add_categories,
            reverse_code=remove_categories),
    ]