# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wikithon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wikithons',
            name='date_time',
        ),
        migrations.AddField(
            model_name='article',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='en_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='words',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=True, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='wikithon',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='wikithon.Wikithons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='articles',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='wikithon.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='contributor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SUBMITTED', 'Submitted'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='articles',
            field=models.ManyToManyField(to='wikithon.Article'),
        ),
        migrations.AddField(
            model_name='team',
            name='invitation_code',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='wikithons',
            name='date',
            field=models.DateField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikithons',
            name='end_time',
            field=models.TimeField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikithons',
            name='start_time',
            field=models.TimeField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wikithons',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
