# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikithon', '0002_auto_20170224_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SUBMITTED', 'Submitted'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='words',
            field=models.IntegerField(null=True),
        ),
    ]
