# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikithon', '0003_auto_20170224_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
    ]
